# Path to zsh config folder
export ZSH=$HOME/.zsh
export KEYTIMEOUT=1
source /usr/local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh

# Source my dotfiles (in explicit order, though my current config doesn't
# really require explicit ordering)
typeset -a DOTFILES
DOTFILES=(
    colors
    exports
    aliases
    functions
    directories
    ssh
    git
    python
    history
    key-bindings
    platform
    ruby
    go
    options
)
for file in $DOTFILES; do
    file=$ZSH/includes/$file
    [[ -f $file ]] && source $file
done
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# z.sh
. /usr/local/etc/profile.d/z.sh

test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh

export NVM_DIR="/Users/bivers/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
